version: "3"

services:
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
      build: ./telegraf
      container_name: marcin_telegraf
      links:
          - influxdb
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
      privileged: true
      restart: always
      env_file:
          - .env
      depends_on:
          - influxdb


  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:
