name: Docker Security Tests

on:
    push:
        branches:
            - main

jobs:
    security_scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
                uses: actions/checkout@v2

            - name: Build Docker image
                run: docker-compose build

            - name: Run Trivy vulnerability scan for InfluxDB
                run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy --cache-dir /root/.cache/trivy --no-progress influxdb:latest

            - name: Run Trivy vulnerability scan for Grafana
                run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy --cache-dir /root/.cache/trivy  --no-progress grafana/grafana-oss:latest

            - name: Install Checkov
                run: pip install checkov

            - name: Run Checkov
                run: checkov --dockerfile telegraf/Dockerfile
